kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: sa-to-custom-scc
    namespace: superset
subjects:
    - kind: ServiceAccount
      name: superset
roleRef:
    kind: Role
    name: custom-scc
    apiGroup: rbac.authorization.k8s.io
